###

GET http://localhost:3000/memberships
###

DELETE  http://localhost:3000/memberships/620a6f2aacd04d05d26283af
###

POST  http://localhost:3000/memberships
Content-Type: application/json

{
  "name": "Gold",
  "price": 6.99,
  "description": "This is 90 days basic membership"
}
