###

GET http://localhost:3000/memberships
###

POST  http://localhost:3000/memberships
Content-Type: application/json

{
  "name": "Bronze",
  "price": 2.99,
  "description": "This is 30 days basic membership"
}
